### ISSUE TITLE
在训练模型的跑了一会的时候报错  ？

### ISSUE THREAD

**Issue by Python-time** [nickliqian/cnn_captcha#122]
Traceback (most recent call last):
  File "train_model.py", line 274, in <module>
    main()
  File "train_model.py", line 269, in main
    tm.train_cnn()  # 开始训练模型
  File "train_model.py", line 174, in train_cnn
    batch_x, batch_y = self.get_batch(i, size=self.train_batch_size)
  File "train_model.py", line 106, in get_batch
    batch_x[i, :] = image_array.flatten() / 255  # flatten 转为一维
ValueError: could not broadcast input array from shape (3000) into shape (3600)
You have mail in /var/spool/mail/root

**Comment by reporter-law** [comment]
请问解决了吗？

**Comment by weekthree** [comment]
我开始也报这个错，后来发现 是因为我在 sample\test目录放了一张和配置文件尺寸不一样的图片。移除掉就可以了
