### ISSUE TITLE
请问大神我把图片大小改成100*200，代码怎么修改，还有增加大写字母，代码怎么修改

### ISSUE THREAD

**Issue by blankandwhite** [nickliqian/cnn_captcha#150]

**Comment by sayasora** [comment]
配置的json不是写了么  看README啊

**Comment by mgaic** [comment]
仅仅修改两个配置文件中的图片的宽高 跑tensorflow会报错 宽高只能固定给100x60吗

**Comment by sayasora** [comment]
不会报错 可能你不小心把逗号啥的删掉了 我改了也能跑的 你验证码生成的宽高都要改




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "15872998154"<notifications@github.com&gt;; 
发送时间: 2020年7月22日(星期三) 晚上6:03
收件人: "nickliqian/cnn_captcha"<cnn_captcha@noreply.github.com&gt;; 
抄送: "sayasorasagiri"<746643780@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [nickliqian/cnn_captcha] 请问大神我把图片大小改成100*200，代码怎么修改，还有增加大写字母，代码怎么修改 (#150)





 
仅仅修改两个配置文件中的图片的宽高 跑tensorflow会报错 宽高只能固定给100x60吗

**Comment by mgaic** [comment]
我仅仅把源码中的两个json文件中的宽高改成了 120x60 跑的话就报错如下　
-->图片尺寸: 60 X 120
-->验证码长度: 4
-->验证码共36类 ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
-->使用测试集为 sample/train/
-->使验证集为 sample/test/
>>> Start model test
>>> input batch images shape: (100, 7200)
>>> input batch labels shape: (100, 144)
>>> input x: Tensor("Reshape:0", shape=(?, 60, 120, 1), dtype=float32)
WARNING:tensorflow:From /home/youmi/project/cnn_captcha/.venv/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
>>> convolution 3:  (?, 8, 15, 128)
>>> input batch predict shape: (?, 144)
>>> End model test
2020-07-23 09:55:45.200874: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/home/youmi/project/cnn_captcha/.venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/youmi/project/cnn_captcha/.venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/youmi/project/cnn_captcha/.venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "/home/youmi/project/cnn_captcha/.venv/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [15360,1024] rhs shape= [13312,1024]
	 [[Node: save/Assign_29 = Assign[T=DT_FLOAT, _class=["loc:@wd1"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](wd1, save/RestoreV2:29)]]

During handling of the above exception, another exception occurred:

**Comment by jarby99** [comment]
删除model文件夹 即可
