### ISSUE TITLE
用自己的生成的验证码就报错了

### ISSUE THREAD

**Issue by Reloss** [nickliqian/cnn_captcha#58]
E:\U22soft\PyCharm\workspace\venv\Scripts\python.exe E:/U22soft/PyCharm/workspace/cnn_captcha-master/train_model.py
-->图片尺寸: 100 X 180
-->验证码长度: 4
-->验证码共36类 ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
-->使用测试集为 sample/train/
-->使验证集为 sample/test/
>>> Start model test
>>> input batch images shape: (100, 18000)
>>> input batch labels shape: (100, 144)
>>> input x: Tensor("Reshape:0", shape=(?, 100, 180, 1), dtype=float32)
WARNING:tensorflow:From E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
>>> convolution 3:  (?, 13, 23, 128)
>>> input batch predict shape: (?, 144)
>>> End model test
2019-06-23 19:28:35.276699: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\client\session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\client\session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [38272,1024] rhs shape= [13312,1024]
	 [[Node: save/Assign_29 = Assign[T=DT_FLOAT, _class=["loc:@wd1"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](wd1, save/RestoreV2:29)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/U22soft/PyCharm/workspace/cnn_captcha-master/train_model.py", line 268, in <module>
    main()
  File "E:/U22soft/PyCharm/workspace/cnn_captcha-master/train_model.py", line 263, in main
    tm.train_cnn()  # 开始训练模型
  File "E:/U22soft/PyCharm/workspace/cnn_captcha-master/train_model.py", line 160, in train_cnn
    saver.restore(sess, self.model_save_dir)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\training\saver.py", line 1775, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\client\session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    run_metadata)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [38272,1024] rhs shape= [13312,1024]
	 [[Node: save/Assign_29 = Assign[T=DT_FLOAT, _class=["loc:@wd1"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](wd1, save/RestoreV2:29)]]

Caused by op 'save/Assign_29', defined at:
  File "E:/U22soft/PyCharm/workspace/cnn_captcha-master/train_model.py", line 268, in <module>
    main()
  File "E:/U22soft/PyCharm/workspace/cnn_captcha-master/train_model.py", line 263, in main
    tm.train_cnn()  # 开始训练模型
  File "E:/U22soft/PyCharm/workspace/cnn_captcha-master/train_model.py", line 153, in train_cnn
    saver = tf.train.Saver()
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\training\saver.py", line 1311, in __init__
    self.build()
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\training\saver.py", line 1320, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\training\saver.py", line 1357, in _build
    build_save=build_save, build_restore=build_restore)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\training\saver.py", line 809, in _build_internal
    restore_sequentially, reshape)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\training\saver.py", line 470, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\training\saver.py", line 162, in restore
    self.op.get_shape().is_fully_defined())
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\ops\state_ops.py", line 281, in assign
    validate_shape=validate_shape)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 64, in assign
    use_locking=use_locking, name=name)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 3290, in create_op
    op_def=op_def)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [38272,1024] rhs shape= [13312,1024]
	 [[Node: save/Assign_29 = Assign[T=DT_FLOAT, _class=["loc:@wd1"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](wd1, save/RestoreV2:29)]]

Process finished with exit code 1

**Comment by Reloss** [comment]
E:\U22soft\PyCharm\workspace\venv\Scripts\python.exe E:/U22soft/PyCharm/workspace/cnn_captcha-master/train_model.py
-->图片尺寸: 100 X 180
-->验证码长度: 4
-->验证码共36类 ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
-->使用测试集为 sample/train/
-->使验证集为 sample/test/
>>> Start model test
>>> input batch images shape: (100, 18000)
>>> input batch labels shape: (100, 144)
>>> input x: Tensor("Reshape:0", shape=(?, 100, 180, 1), dtype=float32)
WARNING:tensorflow:From E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
>>> convolution 3:  (?, 13, 23, 128)
>>> input batch predict shape: (?, 144)
>>> End model test
2019-06-23 19:28:35.276699: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\client\session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\client\session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [38272,1024] rhs shape= [13312,1024]
	 [[Node: save/Assign_29 = Assign[T=DT_FLOAT, _class=["loc:@wd1"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](wd1, save/RestoreV2:29)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/U22soft/PyCharm/workspace/cnn_captcha-master/train_model.py", line 268, in <module>
    main()
  File "E:/U22soft/PyCharm/workspace/cnn_captcha-master/train_model.py", line 263, in main
    tm.train_cnn()  # 开始训练模型
  File "E:/U22soft/PyCharm/workspace/cnn_captcha-master/train_model.py", line 160, in train_cnn
    saver.restore(sess, self.model_save_dir)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\training\saver.py", line 1775, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\client\session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    run_metadata)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [38272,1024] rhs shape= [13312,1024]
	 [[Node: save/Assign_29 = Assign[T=DT_FLOAT, _class=["loc:@wd1"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](wd1, save/RestoreV2:29)]]

Caused by op 'save/Assign_29', defined at:
  File "E:/U22soft/PyCharm/workspace/cnn_captcha-master/train_model.py", line 268, in <module>
    main()
  File "E:/U22soft/PyCharm/workspace/cnn_captcha-master/train_model.py", line 263, in main
    tm.train_cnn()  # 开始训练模型
  File "E:/U22soft/PyCharm/workspace/cnn_captcha-master/train_model.py", line 153, in train_cnn
    saver = tf.train.Saver()
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\training\saver.py", line 1311, in __init__
    self.build()
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\training\saver.py", line 1320, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\training\saver.py", line 1357, in _build
    build_save=build_save, build_restore=build_restore)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\training\saver.py", line 809, in _build_internal
    restore_sequentially, reshape)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\training\saver.py", line 470, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\training\saver.py", line 162, in restore
    self.op.get_shape().is_fully_defined())
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\ops\state_ops.py", line 281, in assign
    validate_shape=validate_shape)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 64, in assign
    use_locking=use_locking, name=name)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 3290, in create_op
    op_def=op_def)
  File "E:\U22soft\PyCharm\workspace\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [38272,1024] rhs shape= [13312,1024]
	 [[Node: save/Assign_29 = Assign[T=DT_FLOAT, _class=["loc:@wd1"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](wd1, save/RestoreV2:29)]]


Process finished with exit code 1

**Comment by nickliqian** [comment]
图片尺寸不一致导致的报错
目前不支持不同尺寸的图片的混合训练

**Comment by Reloss** [comment]
我之前用别的尺寸训练了一次，后来又用自己拉的图片训练然后就报错，之后我重新拉了个用新尺寸就没事了，不过还是谢谢帮助啊
