### ISSUE TITLE
执行到这一步就执行不下去了，是为啥呀

### ISSUE THREAD

**Issue by zhushichuan** [nickliqian/cnn_captcha#72]
![image](https://user-images.githubusercontent.com/27287970/61351314-e7de9780-a89c-11e9-8258-314aac52d041.png)

**Comment by zhushichuan** [comment]
然后。。
![image](https://user-images.githubusercontent.com/27287970/61351351-06449300-a89d-11e9-9495-746932f8f8b6.png)

就这样了

**Comment by zhushichuan** [comment]
Traceback (most recent call last):
  File "D:\pythonproject\venv\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "D:\pythonproject\venv\lib\site-packages\tensorflow\python\client\session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\pythonproject\venv\lib\site-packages\tensorflow\python\client\session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "D:\pythonproject\venv\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[128,64,30,50] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[Node: Conv2D_1 = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Conv2D_1-0-TransposeNHWCToNCHW-LayoutOptimizer, wc2/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: cost/Mean/_33 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_579_cost/Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/d
evice:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_model.py", line 268, in <module>
    main()
  File "train_model.py", line 263, in main
    tm.train_cnn()  # 开始训练模型
  File "train_model.py", line 174, in train_cnn
    feed_dict={self.X: batch_x, self.Y: batch_y, self.keep_prob: 0.75})
  File "D:\pythonproject\venv\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "D:\pythonproject\venv\lib\site-packages\tensorflow\python\client\session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\pythonproject\venv\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    run_metadata)
  File "D:\pythonproject\venv\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[128,64,30,50] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[Node: Conv2D_1 = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Conv2D_1-0-TransposeNHWCToNCHW-LayoutOptimizer, wc2/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: cost/Mean/_33 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_579_cost/Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/d
evice:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


Caused by op 'Conv2D_1', defined at:
  File "train_model.py", line 268, in <module>
    main()
  File "train_model.py", line 263, in main
    tm.train_cnn()  # 开始训练模型
  File "train_model.py", line 133, in train_cnn
    y_predict = self.model()
  File "D:\pythonproject\a\cnn_captcha\cnnlib\network.py", line 73, in model
    conv2 = tf.nn.relu(tf.nn.bias_add(tf.nn.conv2d(conv1, wc2, strides=[1, 1, 1, 1], padding='SAME'), bc2))
  File "D:\pythonproject\venv\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1039, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "D:\pythonproject\venv\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\pythonproject\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 3290, in create_op
    op_def=op_def)
  File "D:\pythonproject\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[128,64,30,50] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[Node: Conv2D_1 = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Conv2D_1-0-TransposeNHWCToNCHW-LayoutOptimizer, wc2/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: cost/Mean/_33 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_579_cost/Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/d
evice:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

新的错误又来了

**Comment by nickliqian** [comment]
参考以下
#73
