### ISSUE TITLE
大佬，报错TypeError: unsupported operand type(s) for /: 'PngImageFile' and 'int'

### ISSUE THREAD

**Issue by cncbec** [nickliqian/cnn_captcha#82]
**错误内容如下：**
Traceback (most recent call last):
  File "train_model.py", line 268, in <module>
    main()
  File "train_model.py", line 263, in main
    tm.train_cnn()  # 开始训练模型
  File "train_model.py", line 171, in train_cnn
    batch_x, batch_y = self.get_batch(i, size=128)
  File "train_model.py", line 103, in get_batch
    batch_x[i, :] = image_array.flatten() / 255  # flatten 转为一维
TypeError: unsupported operand type(s) for /: 'PngImageFile' and 'int'

**请问该如何解决？**

**Comment by aiex718** [comment]
Maybe image damaged, I add some image check inside verify_and_split_data.py , from
```python
try:
    img = Image.open(file_path)
except OSError:
    bad_img.append((index, img_name, "图片无法正常打开"))
continue
````
to
```python
try:
    img = Image.open(file_path)
    captcha_array = np.array(img)
    v = captcha_array.flatten() / 255
except :
    bad_img.append((index, img_name, "图片无法正常打开"))
    continue
```
