### ISSUE TITLE
执行train_model.py，出错是什么问题

### ISSUE THREAD

**Issue by rickyYao** [nickliqian/cnn_captcha#9]
convolution 1:  Tensor("dropout/mul:0", shape=(?, 27, 65, 32), dtype=float32)
Backend TkAgg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.4\helpers\pydev\pydevd.py", line 1668, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.4\helpers\pydev\pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.4\helpers\pydev\pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Project/cnn_captcha-master/train_model.py", line 282, in <module>
    main()
  File "D:/Project/cnn_captcha-master/train_model.py", line 277, in main
    tm.train_cnn()  # 开始训练模型
  File "D:/Project/cnn_captcha-master/train_model.py", line 196, in train_cnn
    y_predict = self.model()
  File "D:/Project/cnn_captcha-master/train_model.py", line 157, in model
    print(">>> convolution 1: ", conv1.shape)
AttributeError: 'Tensor' object has no attribute 'shape'

**Comment by nickliqian** [comment]
@rickyYao 
请提供你使用的tensorflow版本

**Comment by rickyYao** [comment]
Dear nick
  我的tensorflow版本是(0.12.0rc0)，我修改了代码，可以编译通过了，但是训练后的识别率很低。
附件是我的代码，麻烦帮我看一下。


谢谢
ricky






在 2018-11-27 20:20:10，"Nick Li" <notifications@github.com> 写道：


@rickyYao
请提供你使用的tensorflow版本

**Comment by nickliqian** [comment]
没有看到你的附件。
提问请详细介绍你遇到的问题的前因后果。
