### ISSUE TITLE
Failed to get convolution algorithm.

### ISSUE THREAD

**Issue by QQ2737499951** [nickliqian/cnn_captcha#94]
不知道是否与版本有关？

Win-10
Python 3.68
TensorFlow-GPU 1.13.1
CUDA 10.0
cuDNN 7.5.0
==========

"D:\Program Files\Python368\python.exe" B:/Tensorflow/cnn_captcha/train_model.py
-->图片尺寸: 62 X 200
-->验证码长度: 4
-->验证码共36类 ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
-->使用测试集为 sample/train/
-->使验证集为 sample/test/
>>> Start model test
>>> input batch images shape: (100, 12400)
>>> input batch labels shape: (100, 144)
>>> input x: Tensor("Reshape:0", shape=(?, 62, 200, 1), dtype=float32)

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From D:\Program Files\Python368\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From B:\Tensorflow\cnn_captcha\cnnlib\network.py:67: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
>>> convolution 3:  (?, 8, 25, 128)
>>> input batch predict shape: (?, 144)
>>> End model test
2019-09-26 22:35:55.483601: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-09-26 22:35:55.661934: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 11.00GiB freeMemory: 9.11GiB
2019-09-26 22:35:55.662233: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-09-26 22:35:56.114095: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-09-26 22:35:56.114269: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-09-26 22:35:56.114366: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-09-26 22:35:56.114568: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8791 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2019-09-26 22:35:57.380956: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library cublas64_100.dll locally
2019-09-26 22:35:57.582535: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-09-26 22:35:57.582914: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-09-26 22:35:57.583942: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-09-26 22:35:57.584188: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-09-26 22:35:57.584525: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-09-26 22:35:57.584732: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-09-26 22:35:58.408824: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2019-09-26 22:35:58.409371: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
Traceback (most recent call last):
  File "D:\Program Files\Python368\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "D:\Program Files\Python368\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\Program Files\Python368\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node Conv2D}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "B:/Tensorflow/cnn_captcha/train_model.py", line 279, in <module>
    main()
  File "B:/Tensorflow/cnn_captcha/train_model.py", line 274, in main
    tm.train_cnn()  # 开始训练模型
  File "B:/Tensorflow/cnn_captcha/train_model.py", line 182, in train_cnn
    feed_dict={self.X: batch_x, self.Y: batch_y, self.keep_prob: 0.75})
  File "D:\Program Files\Python368\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "D:\Program Files\Python368\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Program Files\Python368\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "D:\Program Files\Python368\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node Conv2D (defined at B:\Tensorflow\cnn_captcha\cnnlib\network.py:65) ]]

Caused by op 'Conv2D', defined at:
  File "B:/Tensorflow/cnn_captcha/train_model.py", line 279, in <module>
    main()
  File "B:/Tensorflow/cnn_captcha/train_model.py", line 274, in main
    tm.train_cnn()  # 开始训练模型
  File "B:/Tensorflow/cnn_captcha/train_model.py", line 141, in train_cnn
    y_predict = self.model()
  File "B:\Tensorflow\cnn_captcha\cnnlib\network.py", line 65, in model
    conv1 = tf.nn.relu(tf.nn.bias_add(tf.nn.conv2d(x, wc1, strides=[1, 1, 1, 1], padding='SAME'), bc1))
  File "D:\Program Files\Python368\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1113, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "D:\Program Files\Python368\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "D:\Program Files\Python368\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "D:\Program Files\Python368\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "D:\Program Files\Python368\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node Conv2D (defined at B:\Tensorflow\cnn_captcha\cnnlib\network.py:65) ]]

**Comment by QQ2737499951** [comment]
![image](https://user-images.githubusercontent.com/33048209/65699158-418aeb80-e0b0-11e9-9fb3-7d2797068d6c.png)

**Comment by gengzll** [comment]
你解决这个问题了嘛  我也是相同的情况

**Comment by QQ2737499951** [comment]
有这个问题的，请加我qq2737499951 沟通一下，谢谢
